# Generated by Django 4.0.6 on 2024-07-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام محصصول')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('photo', models.ImageField(upload_to='cinematicket/', verbose_name='تصویر محصول')),
                ('rate', models.IntegerField(verbose_name='امتیاز محصول')),
                ('time', models.IntegerField(verbose_name='زمان انتظار')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
            ],
        ),
    ]
