# Generated by Django 4.0.6 on 2024-08-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinematicket', '0003_alter_food_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان تگ ')),
                ('slug', models.CharField(max_length=50, verbose_name='عنوان تگ به لاتین ')),
                ('edited_date', models.DateField(auto_now=True, verbose_name='اخرین بروزرسانی')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='زمان انشار')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='food', to='cinematicket.tag', verbose_name='تگ های محصول'),
        ),
    ]
