# Generated by Django 4.0.6 on 2024-08-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinematicket', '0004_tag_food_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.AddField(
            model_name='tag',
            name='slug_tag',
            field=models.SlugField(blank=True, null='True', verbose_name='عنوان تگ به لاتین '),
            preserve_default='True',
        ),
    ]
